name: Publish

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: https://erickcestari.github.io/interactive-BNF/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/configure-pages@v3
      - run: deno task build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: static
      - id: deployment
        uses: actions/deploy-pages@v2
